### PR TITLE
Create run-sieve.yml

### PR DESCRIPTION
**Pull request by jerrinsg**
Creating a reusable workflow to test controllers with Sieve. The workflows takes as input the GitHub repo path and subdirectory (optional) that contains the test files  needed for testing a controller. It supports both linux and macos Github runners. The workflow then does the following actions:
1. Build controller with Sieve instrumentation in "learn" mode
2. Run the controller in "learn" mode with the test workload
3. Build controller with Sieve instrumentation in "test" mode
4. Run controller in "test" mode with the provided test workload and sieve-injected perturbations to identify any bugs.

### CODE REVIEW

**Comment by jerrinsg** [comment]
Some test runs run with this workflow:

1. Testing kapp-controller with a simple workload:
    a. linux - https://github.com/jerrinsg/sieve-action-test/actions/runs/5061681702/jobs/9086227941
    b. mac - https://github.com/jerrinsg/sieve-action-test/actions/runs/5061682278/jobs/9086228910

2. Testing kapp-controller with Cassandra deployment:
    a. linux - https://github.com/jerrinsg/sieve-action-test/actions/runs/5065419614/jobs/9093979106
    b. mac - https://github.com/jerrinsg/sieve-action-test/actions/runs/5070530195/jobs/9105688362

2b. though fails at getting the test workload deployed with kapp's default timeout of 15 minutes. The default GitHub macos runners seem to be pretty slow so users probably would need to use a self-hosted runner (if using macos) to get a fairly complex workload deployed and tested with the reusable workflow.

**Comment by marshtompsxd** [comment]
@jerrinsg Does this workflow assume that we already have the config file for testing the controller? (like the Dockerfile, build.sh, and so on)

**Comment by jerrinsg** [comment]
> @jerrinsg Does this workflow assume that we already have the config file (under `examples` directory) for testing the controller? (like the Dockerfile, build.sh, and so on)

The input to the workflow is a Github repo URL and subdirectory. The workflow then assumes that all the files needed for testing the controller will be in the provided Github repo. E.g. for testing the kapp controller, an invocation could look like below ([ref](https://github.com/jerrinsg/sieve-action-test/blob/main/.github/workflows/sieve-kapp-simple-ubuntu.yml))
```
    uses: jerrinsg/sieve/.github/workflows/run-sieve.yml@main
    with:
      controller-name: kapp-controller
      github-repo: https://github.com/jerrinsg/sieve-action-test.git
      subdirectory: kapp-controller-simple
```

So all the files needed for testing kapp-controller should be in https://github.com/jerrinsg/sieve-action-test/tree/main/kapp-controller-simple. The workflow file doesn't use any pre-existing files in the `example` directory of the sieve project. It deletes all the files in `example` directory first, copies over the new files to be tested, and then does the testing.

**Comment by marshtompsxd** [comment]
LGTM

**Pull request merged**
